--- #YAML:1.0
name:               Cisco-UCS
version:            0.28
abstract:           A Perl interface to the Cisco UCS XML API
author:
    - Luke Poskitt <ltp@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cisco::UCS::Blade:    0
    Cisco::UCS::Chassis:  0
    Cisco::UCS::Fault:    0
    Cisco::UCS::FEX:      0
    Cisco::UCS::Interconnect:  0
    Cisco::UCS::MgmtEntity:  0
    Cisco::UCS::ServiceProfile:  0
    LWP:                  0
    Test::More:           0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
